variables:
- group: Semgrep_Variables_Victor

resources:
  repositories: 
    - repository: udacity-cloud-devops-projects
      type: github
      name: victor-ok/udacity-cloud-devops-projects
      ref: refs/heads/main
      # ref: ${{ variables['Build.SourceBranch'] }}
      endpoint: victor-ok # Please change the name of service connection here. More details can be found in additonal information below.

jobs:
- job: Semgrep_Include
  strategy:
   matrix:
     repo1:
       repo: 'cloud-devops-ci-cd-udapeople'
     repo2:
       repo: 'cloud-devops-cloudformation'       
       
  steps:
    - script: |
        python -m pip install --upgrade pip
        pip install semgrep
        if [ $(Build.SourceBranchName) = "main" ]; then
            echo "Semgrep full scan"
            semgrep login
            semgrep ci --include $(repo)
        elif [ $(Build.SourceBranchName) != "main" ]; then
            echo "Semgrep diff scan"
            echo "Pull Request Scan from branch: $(Build.SourceBranchName)"
            git fetch origin main:origin/main
            semgrep login
            semgrep ci --include $(repo)
        fi
      env:
        SEMGREP_APP_TOKEN: $(SEMGREP_APP_TOKEN)
        SEMGREP_REPO_DISPLAY_NAME: monorepo-test--$(repo)    

- job: Semgrep_Exclude
  steps:
    - script: |
        python -m pip install --upgrade pip
        pip install semgrep
        if [ $(Build.SourceBranchName) = "main" ]; then
            echo "Semgrep full scan"
            semgrep login
            semgrep ci
        elif [ $(Build.SourceBranchName) != "main" ]; then
            echo "Semgrep diff scan"
            echo "Pull Request Scan from branch: $(Build.SourceBranchName)"
            git fetch origin main:origin/main
            semgrep login
            semgrep ci
        fi
      env:
        SEMGREP_APP_TOKEN: $(SEMGREP_APP_TOKEN)